linux_docker_builder:
  script: docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-linux . -f Dockerfile

rpi_docker_builder:
  script: docker build -t $CIRRUS_REPO_FULL_NAME:cirrus-rpi . -f Dockerfile.rpi
