#!/bin/sh

YI_HOME="/home/yi"
CONF_FILE="${YI_HOME}/etc/system.conf"

get_config()
{
	key=$1
	grep -w $1 $CONF_FILE | cut -d "=" -f2
}

if [[ $(get_config PROXYCHAINSNG) == "yes" ]] ; then
	${YI_HOME}/bin/proxychains4 ./cloudAPI_real "$@"
else
	./cloudAPI_real "$@"
fi
